name: "Create release"

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  validate_main_module:
    uses: ./.github/workflows/validate_module.yml
    name: "Validate module"
    with:
      terraform_version: ${{ vars.TERRAFORM_VERSION }}

  validate_oidc_provider:
    uses: ./.github/workflows/validate_module.yml
    name: "Validate OIDC Provider submodule"
    with:
      terraform_version: ${{ vars.TERRAFORM_VERSION }}
      working-directory: modules/oidc-provider

  validate_gh_actions_example:
    uses: ./.github/workflows/validate_module.yml
    name: "Validate GitHub Actions example"
    with:
      terraform_version: ${{ vars.TERRAFORM_VERSION }}
      working-directory: examples/github-actions

  create_release:
    name: "Create GitHub release"
    runs-on: ubuntu-latest
    needs: [ validate_main_module, validate_oidc_provider, validate_gh_actions_example ]
    permissions:
      contents: write
    steps:
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
