name: "Pull Request"

on:
  pull_request:
    branches:
      - master

jobs:
  validate_main_module:
    uses: ./.github/workflows/validate_module.yml
    name: "Validate module"
    with:
      terraform_version: ${{ vars.TERRAFORM_VERSION }}

  validate_oidc_provider:
    uses: ./.github/workflows/validate_module.yml
    name: "Validate OIDC Provider submodule"
    with:
      terraform_version: ${{ vars.TERRAFORM_VERSION }}
      working-directory: modules/oidc-provider

  validate_gh_actions_example:
    uses: ./.github/workflows/validate_module.yml
    name: "Validate GitHub Actions example"
    with:
      terraform_version: ${{ vars.TERRAFORM_VERSION }}
      working-directory: examples/github-actions

  output_terraform_results:
    name: "Output Terraform results"
    runs-on: ubuntu-latest
    needs: [ validate_main_module, validate_oidc_provider, validate_gh_actions_example ]
    permissions:
      pull-requests: write
      issues: write
    steps:
      - uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        env:
          MODULE_FMT: ${{ needs.validate_main_module.outputs.fmtOutcome }}
          MODULE_INIT: ${{ needs.validate_main_module.outputs.initOutcome }}
          MODULE_VALIDATE: ${{ needs.validate_main_module.outputs.validateOutcome }}
          MODULE_VALIDATE_OUTPUT: ${{ needs.validate_main_module.outputs.validateOutput }}
          OIDC_FMT: ${{ needs.validate_oidc_provider.outputs.fmtOutcome }}
          OIDC_INIT: ${{ needs.validate_oidc_provider.outputs.initOutcome }}
          OIDC_VALIDATE: ${{ needs.validate_oidc_provider.outputs.validateOutcome }}
          OIDC_VALIDATE_OUTPUT: ${{ needs.validate_oidc_provider.outputs.validateOutput }}
          EXAMPLE_FMT: ${{ needs.validate_gh_actions_example.outputs.fmtOutcome }}
          EXAMPLE_INIT: ${{ needs.validate_gh_actions_example.outputs.initOutcome }}
          EXAMPLE_VALIDATE: ${{ needs.validate_gh_actions_example.outputs.validateOutcome }}
          EXAMPLE_VALIDATE_OUTPUT: ${{ needs.validate_gh_actions_example.outputs.validateOutput }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // 1. Retrieve existing bot comments for the PR
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            })
            const title = 'Terraform Results'
            const botComment = comments.find(comment => {
              return comment.user.type === 'Bot' && comment.body.includes(title)
            })

            // 2. Prepare format of the comment
            const output = `## ${title}
            
            ### Module
            #### Terraform fmt 🖌\`${{ env.MODULE_FMT }}\`
            #### Terraform init ⚙️\`${{ env.MODULE_INIT }}\`
            #### Terraform validate 🤖\`${{ env.MODULE_VALIDATE }}\`
            <details><summary>Validation Output</summary>

            \`\`\`\n
            ${{ env.MODULE_VALIDATE_OUTPUT }}
            \`\`\`

            </details>
            
            ### Submodule - oidc-provider 
            #### Terraform fmt 🖌\`${{ env.OIDC_FMT }}\`
            #### Terraform init ⚙️\`${{ env.OIDC_INIT }}\`
            #### Terraform validate 🤖\`${{ env.OIDC_VALIDATE }}\`
            <details><summary>Validation Output</summary>

            \`\`\`\n
            ${{ env.OIDC_VALIDATE_OUTPUT }}
            \`\`\`

            </details>
            
            ### Example - GitHub Actions 
            #### Terraform fmt 🖌\`${{ env.EXAMPLE_FMT }}\`
            #### Terraform init ⚙️\`${{ env.EXAMPLE_INIT }}\`
            #### Terraform validate 🤖\`${{ env.EXAMPLE_VALIDATE }}\`
            <details><summary>Validation Output</summary>

            \`\`\`\n
            ${{ env.EXAMPLE_VALIDATE_OUTPUT }}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;

            // 3. If we have a comment, update it, otherwise create a new one
            if (botComment) {
              github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: output
              })
            } else {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
              })
            }