on:
  workflow_call:
    inputs:
      terraform_version:
        description: 'Terraform version to use'
        required: true
        default: 'latest'
        type: string
      working-directory:
        description: 'Working directory to run Terraform commands in'
        required: false
        default: '.'
        type: string
      runs-on:
        description: 'The type of machine to run the job on'
        required: false
        default: 'ubuntu-latest'
        type: string
    outputs:
      fmtOutcome: ${{ jobs.validate.outputs.fmtOutcome }}
      initOutcome: ${{ jobs.validate.outputs.initOutcome }}
      validateOutcome: ${{ jobs.validate.outputs.validateOutcome }}
      validateOutput: ${{ jobs.validate.outputs.validateOutput }}

jobs:
  validate:
    runs-on: ${{ inputs.runs-on }}
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    outputs:
      fmtOutcome: ${{ steps.fmt.outcome }}
      initOutcome: ${{ steps.init.outcome }}
      validateOutcome: ${{ steps.validate.outcome}}
      validateOutput: ${{ steps.validate.outputs.stdout}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ vars.TERRAFORM_VERSION }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color